---

- name: Ensure iptables is installed (debian)
  apt: pkg=iptables
  when: ansible_os_family == 'Debian'

- name: Ensure iptables is installed (redhat)
  yum: pkg=iptables
  when: ansible_os_family == 'RedHat'

- name: Prepare iptables rules
  template: dest={{iptables_rule_path}} src=iptables.rules.j2 owner=root group=root mode=0744
  notify:
    - iptables load

- stat: path=/etc/network/if-up.d/iptables_load
  register: iptables_load_exist

- name: Autoload the rules
  template: src=iptables_load.j2 dest=/etc/network/if-up.d/iptables_load owner=root group=root mode=751
  when: iptables_load_exist.stat.exists
